// Generated by CoffeeScript 1.6.3
exports.auth_code = function(x, y) {
  var S, ss;
  S = x;
  ss = y;
  if (S(ss.storage.wb_token).isEmpty()) {
    console.log("No token found");
    return false;
  } else {
    console.log("Token is there");
    console.log(ss.storage.wb_token);
    return true;
  }
};
