// Generated by CoffeeScript 1.6.3
var Request, S, helpers, main_panel, panels, self, ss, tabs, widget, widgets;

self = require('sdk/self');

widgets = require('sdk/widget');

panels = require('sdk/panel');

tabs = require('sdk/tabs');

Request = require('sdk/request').Request;

ss = require("sdk/simple-storage");

S = require('./libs/string.min.js');

helpers = require('./helpers.js');

main_panel = panels.Panel({
  width: 300,
  height: 400,
  contentURL: self.data.url("templates/main_page.html"),
  contentScriptFile: self.data.url("main_panel.js")
});

widget = widgets.Widget({
  id: "foxo",
  label: "foxo helper",
  contentURL: self.data.url("assets/img/weibo_ico_48x48.png"),
  panel: main_panel
});

main_panel.port.on('click_m_btn', function() {
  tabs.open({
    url: "https://api.weibo.com/oauth2/authorize?\nclient_id=1416063824&\nredirect_uri=https://api.weibo.com/oauth2/default.html&\nresponse_type=code",
    onReady: function(tab) {
      var code, n, _ref;
      if (S(tab.url).include('default.html?code=')) {
        _ref = tab.url.split('='), n = _ref[0], code = _ref[1];
        Request({
          url: "https://api.weibo.com/oauth2/access_token?\nclient_id=1416063824&\nclient_secret=40d9b5dbe0b1c62172d341333be7832b&\ngrant_type=authorization_code&\nredirect_uri=https://api.weibo.com/oauth2/default.html&\ncode=" + code,
          onComplete: function(res) {
            res = JSON.parse(res.text);
            ss.storage.token = res.access_token;
            return ss.storage.token_remind_in = res.token_remind_in;
          }
        }).post();
        tab.close();
      }
    }
  });
});
